const ENVS = import.meta.env;

const APP_ENV: string = ENVS.VITE_MODE;

const TELEGRAM_BOT_TOKEN: string = ENVS.VITE_TELEGRAM_BOT_TOKEN;
const CDN_URL_ICONS: string = ENVS.VITE_CDN_URL_ICONS;

export { APP_ENV, TELEGRAM_BOT_TOKEN, CDN_URL_ICONS };
